### ISSUE TITLE
AtlantaLayout Dataset link cannot be opened

### ISSUE THREAD

**Issue by busning** [crs4/AtlantaNet#1]
When I use the link: https://vicserver.crs4.it/atlantanet/atlantalayout.zip

It shows as follows:

Not Found

The requested URL was not found on this server.

Apache/2.4.18 (Ubuntu) Server at vicserver.crs4.it Port 443

**Comment by giannipint** [comment]
The file is now available on the server.
Please update the GitHub repository at the last relase.
