### ISSUE TITLE
Custom Images Inference

### ISSUE THREAD

**Issue by marcomiglionico94** [crs4/AtlantaNet#3]
I tried to use custom 360 panorama images for inference using Resnet101 pre trained model. The model seems to work fine and the visualization too. The only issue I am having is that the layout seems to be `mirrored`. What i mean is that what should be on the left is on the right and vice versa. Do you know how can i fix this issue?
Thanks

**Comment by giannipint** [comment]
Hello, actually the mesh is mirrored to be consistent with the convention of layouts annotated by matterportLayout and HorizonNet, in order to simplify numerical comparison. The easiest way to mirror the mesh is to export to obj and apply the mirror with tools such as Meshlab.

**Comment by abner2015** [comment]
http://pan.baidu.com/s/1hqGbyQS
